---
name: Run Integration
run-name: "Patched Keycloak tgz for ${{ github.event.repository.name }} - ${{ github.run_number }} - ${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      keycloak-tag:
        description: "Keycloak version tag"
        required: true
        default: "26.3.2"
      tag:
        description: "Tag to create for patched build"
        required: true
        default: "keycloak-26.3.2-patched"
      forceCreate:
        type: boolean
        description: "Force tag creation"
        required: false
        default: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # - name: Create a New Tag
      #   uses: netcracker/qubership-workflow-hub/actions/tag-action@main
      #   with:
      #     ref: ${{ github.ref_name }}
      #     tag-name: ${{ inputs.tag }}
      #     force-create: ${{ inputs.forceCreate }}
      #     switch-to-tag: true
      #     create-release: true
      #     skip-checkout: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Clean workspace
      #   run: rm -rf ./*

      # - name: Checkout Keycloak source code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: keycloak/keycloak
      #     ref: ${{ inputs.keycloak-tag }}

      # - name: Checkout patches
      #   uses: actions/checkout@v4
      #   with:
      #     path: ./keycloak-patches
      #     ref: ${{ inputs.tag }}

      # - name: Apply patches
      #   run: |
      #     cd ${GITHUB_WORKSPACE}
      #     for p in ./keycloak-patches/keycloak-patches/${{ inputs.keycloak-tag }}/*.patch; do
      #       echo "Applying $p…"
      #       git apply -p1 --ignore-space-change --ignore-whitespace "$p"
      #     done
      #     rm -rf ./keycloak-patches

      # - name: Set up Maven
      #   uses: stCarolas/setup-maven@v5
      #   with:
      #     maven-version: 3.9.8

      # - name: Build Keycloak (patched)
      #   uses: ./.github/actions/build-keycloak
      #   with:
      #     upload-m2-repo: true
      #     upload-dist: true
      #     workspace: keycloak-src

      # - name: Upload .tgz as release asset
      #   uses: netcracker/qubership-workflow-hub/actions/assets-action@main
      #   with:
      #     tag: ${{ inputs.tag }}
      #     item-path: ./quarkus/dist/target/keycloak-*.tar.gz
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger custom event
        uses: netcracker/qubership-workflow-hub/actions/custom-event@v2.0.1
        with:
          event-type: "integration-patched-keycloak-built"
          #client-payload: '{ "url": "https://github.com/${{ github.repository }}/releases/download/${{ inputs.tag }}/keycloak-${{ inputs.tag }}.tar.gz" }'
          client-payload: |
            { "url": "https://github.com/nookyo/keycloak-patches/releases/download/keycloak-26.3.2-patched/keycloak-keycloak-26.3.2-patched.tar.gz" ,
               "tag": "${{ inputs.keycloak-tag }}",
               "patchedTag": "${{ inputs.tag }}",
               "repo": "${{ github.repository }}",
               "owner": "${{ github.repository_owner }}"
               "forceCreate": "${{ inputs.forceCreate }}"
            }
          owner: "nookyo"
          repo: "keycloak"
          github-token: ${{ secrets.PAT_FOR_DISPATCH }}
